spring:
  ai:
    vectorstore:
      chroma:
        client:
          host: http://111.229.197.250
          port: 8000
        initialize-schema: true
    ollama:
      base-url: http://localhost:11434
      chat:
        model: gemma3:12b
        options:
          temperature: 0.0
      embedding:
#        model: mofanke/dmeta-embedding-zh
        model: nomic-embed-text:latest
# springdoc-openapi项目配置`
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.bxmdm.ai.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn